services:
  db:
    image: postgres:14
    container_name: microhabitos_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microhabitos_development
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: microhabitos_web
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/microhabitos_development

volumes:
  postgres_data:
